auther:徐梓豪 2016-08-12
Feature:管理员导出账号列表

Background:
	"""
		[{
		"account_type":"体验客户",
		"company_name":"爱昵咖啡有限责任公司",
		"shop_name":"爱昵咖啡",
		"manage_type":"休闲食品",
		"purchase_type":"固定底价",
		"connect_man":"aini",
		"mobile_number":"13813985506",
		"login_account":"aini",
		"password":"123456",
		"valid_time":"2016-07-15"至"2017-07-15",
		"ramarks":"爱昵咖啡客户体验账号"
		},{
		"account_type":"运营",
		"account_name":"运营部门",
		"login_account":"yunying",
		"password":123456,
		"ramarks":"运营部门"
		},{
		"account_type":"体验客户",
		"company_name":"零售价返点客户",
		"shop_name":"零售价返点商店",
		"manage_type":"休闲食品",
		"purchase_type":"零售价返点客户",
		purchase_promotin":"5.00",
		"group_purchase":{
						"weizoom_home":"4.00",
						"weizoom_mum":"3.00",
						"weizoom_baifumei":"1.00",
						"weizoom_club":"2.00",
						"weizoom_shop":"1.42",
						"weizoom_xuesheng":"1.64",
						"weizoom_life":"2.38",
						"weizoom_yijiaren":"4.56",
						"huihuilaila":"3.81"
		}"
		"connect_man":"零售价",
		"mobile_number":"13813985506",
		"login_account":"lingshou",
		"password":"123456",
		"valid_time":"2016-08-15"至"2017-07-15",
		"ramarks":"零售价客户账号"
		}